#pragma once
#include <QStringList>
#include <QVector>
#include <QPair>

namespace TikzWords {

inline const QStringList tikzCommands() {
    static const QStringList list = {
        // ── Basic TikZ/PGF ──
        "addplot", "addplot3", "addlegendentry", "addlegendimage",
        "anchor", "arc", "arrow",
        "ball", "begin", "bend",
        "caption", "circle", "clip", "closedcycle", "coordinate",
        "coordinates", "cos", "cycle",
        "dataset", "datavisualization",
        "definecolor", "def", "draw", "drawplot",
        "edef", "edge", "else", "end", "exp", "expandafter",
        "fill", "filldraw", "flat", "foreach", "forest",
        "getref", "gdef", "global", "graph",
        "hbox", "hfil", "hfill", "hline", "hrule", "hskip", "hspace",
        "if", "ifdim", "ifnum", "ifodd", "ifx",
        "input", "item",
        "label", "let", "line", "lineto", "ln",
        "matrix", "max", "min", "moveleft", "moveright",
        "newcommand", "newcount", "newdimen", "newif", "newwrite",
        "node",
        "par", "parbox", "path", "pattern", "pgfkeys", "pgfmathsetmacro",
        "pgfplotstableread", "pgfplotstabletypeset",
        "pic", "pin", "plot", "protected",
        "relax", "renewcommand", "repeat",
        "scope", "setlength", "shade", "shadedraw",
        "sin", "sqrt",
        "tabular", "text", "tikzset", "tikzstyle", "to",
        "usebox", "usepackage", "usetikzlibrary",
        "vbox", "vertex", "vfil", "vfill", "vrule", "vskip", "vspace",
        "xdef",

        // ── tikz-3dplot ──
        "tdplotsetmaincoords",
        "tdplotsetrotatedcoords",
        "tdplotsetcoord",
        "tdplotsetthetaplanecoords",
        "tdplotdrawarc",
        "tdplotdrawpolytope",
        "tdplotsphericalsurfaceplot",
        "tdplottransformmainscreen",
        "tdplottransformrotatedmain",
        "tdplotdefinepoints",
        "tdplotcalctransformrotmain",
        "tdplotcalctransformmainscreen",

        // ── PGF Math / Keys ──
        "pgfmathtruncatemacro",
        "pgfmathparse",
        "pgfmathresult",
        "pgfmathprintnumber",
        "pgfmathrandominteger",
        "pgfmathsetseed",
        "pgfmathsetlength",
        "pgfmathaddtocounter",
        "pgfmathsetcount",
        "pgfmathsetmacroglobal",
        "pgfmathequalto",
        "pgfmathgreaterthan",
        "pgfmathlessthan",
        "pgfmathapproxequalto",
        "pgfmathnot",
        "pgfkeysvalueof",
        "pgfkeysgetvalue",
        "pgfkeyssetvalue",
        "pgfkeyssetevalue",
        "pgfkeysedef",
        "pgfkeyslet",
        "pgfkeysfiltered",
        "pgfplotsset",
        "pgfplotscreateplotcyclelist",
        "pgfplotstablecreatecol",
        "pgfplotstableset",
        "pgfplotstablegetelem",
        "pgfplotstablegetcolsof",
        "pgfplotstablegetrowsof",
        "pgfplotsforeachungrouped",
        "pgfplotstablevertcat",
        "pgfplotstabletranspose",
        "pgfplotsinvokeforeach",
        "pgfplotsforeach",

        // ── PGF Layer Commands ──
        "pgfdeclarelayer",
        "pgfsetlayers",
        "pgfonlayer",
        "endpgfonlayer",

        // ── PGF Declarations ──
        "pgfdeclareshape",
        "pgfdeclareplotmark",
        "pgfdeclareimage",
        "pgfdeclarepatternformonly",
        "pgfdeclarepattern",
        "pgfdeclaredecoration",
        "pgfdeclarefading",
        "pgfdeclarehorizontalshading",
        "pgfdeclareverticalshading",
        "pgfdeclareradialshading",
        "pgfdeclarefunctionalshading",

        // ── PGF Drawing Primitives ──
        "pgfset",
        "pgfsetlinewidth",
        "pgfsetcolor",
        "pgfsetstrokecolor",
        "pgfsetfillcolor",
        "pgfsetarrow",
        "pgfsetdash",
        "pgfsetbuttcap",
        "pgfsetroundcap",
        "pgfsetrectcap",
        "pgfsetroundjoin",
        "pgfsetbeveljoin",
        "pgfsetmiterjoin",
        "pgfsetmiterlimit",
        "pgftext",
        "pgfnode",
        "pgfcoordinate",
        "pgfpathmoveto",
        "pgfpathlineto",
        "pgfpathcurveto",
        "pgfpathcircle",
        "pgfpathellipse",
        "pgfpathrectangle",
        "pgfpathrectanglecorners",
        "pgfpathgrid",
        "pgfpathclose",
        "pgfpathqcurveto",
        "pgfusepath",
        "pgfuseplotmark",
        "pgfpoint",
        "pgfpointanchor",
        "pgfpointintersectionoflines",
        "pgfpointintersectionofcircles",
        "pgfpointintersectionofcurves",
        "pgfpointadd",
        "pgfpointscale",
        "pgfpointdiff",
        "pgfpointpolar",

        // ── PGF Transformations ──
        "pgftransformshift",
        "pgftransformrotate",
        "pgftransformscale",
        "pgftransformxscale",
        "pgftransformyscale",
        "pgftransformxslant",
        "pgftransformyslant",
        "pgftransformcm",
        "pgftransformreset",
        "pgftransformtriangle",
        "pgftransformnonlinear",

        // ── More TikZ drawing commands ──
        "useasboundingbox",
        "tikztonodes",
        "tikzlastnode",
        "pgfextra",
        "pgfinterruptpath",
        "endpgfinterruptpath",
        "pgfinterruptboundingbox",
        "endpgfinterruptboundingbox",
        "tikzmark",
        "subnode",
        "pgfinterruptpicture",

        // ── Plot/axis ──
        "legend",
        "addplot3",
        "addplot",
        "addplot+",
        "addplot+3",
        "nextgroupplot",

        // ── Math symbols (Greek) ──
        "alpha", "beta", "gamma", "delta", "epsilon", "varepsilon",
        "zeta", "eta", "theta", "vartheta", "iota", "kappa",
        "lambda", "mu", "nu", "xi", "pi", "varpi", "rho", "varrho",
        "sigma", "varsigma", "tau", "upsilon", "phi", "varphi",
        "chi", "psi", "omega",
        "Gamma", "Delta", "Theta", "Lambda", "Xi", "Pi", "Sigma",
        "Upsilon", "Phi", "Psi", "Omega",

        // ── Math operators ──
        "arccos", "arcsin", "arctan", "arg",
        "cot", "coth", "csc", "csch",
        "deg", "det", "dim", "hom", "ker",
        "lg", "lim", "liminf", "limsup", "sup", "inf",
        "max", "min",
        "gcd", "Pr",
        "sec", "sinh", "cosh", "tanh",

        // ── Math delimiters ──
        "left", "right", "big", "Big", "bigg", "Bigg",
        "bigl", "Bigl", "biggl", "Biggl",
        "bigr", "Bigr", "biggr", "Biggr",
        "langle", "rangle",
        "lceil", "rceil", "lfloor", "rfloor",
        "lvert", "rvert", "lVert", "rVert",
        "lgroup", "rgroup",
        "lmoustache", "rmoustache",
        "brace", "brack",
        "bracevert",

        // ── Math accents ──
        "hat", "check", "tilde", "acute", "grave", "dot", "ddot",
        "breve", "bar", "vec", "mathring", "widehat", "widetilde",
        "overline", "underline", "overrightarrow", "overleftarrow",
        "overleftrightarrow", "underrightarrow", "underleftarrow",
        "underleftrightarrow", "overbrace", "underbrace",

        // ── Math fonts / styles ──
        "mathbb", "mathbf", "mathrm", "mathsf", "mathtt",
        "mathit", "mathcal", "mathscr", "mathfrak", "mathbfcal",
        "text", "textnormal", "textbf", "textit", "texttt",
        "textsf", "textsc", "textup", "textmd", "textrm",

        // ── Math misc ──
        "frac", "dfrac", "tfrac", "cfrac", "binom", "dbinom", "tbinom",
        "int", "iint", "iiint", "iiiint", "oint", "oiint", "oiiint",
        "sum", "prod", "coprod",
        "bigcup", "bigcap", "bigvee", "bigwedge",
        "bigoplus", "bigotimes", "bigodot", "biguplus", "bigsqcup",
        "partial", "nabla", "triangle", "square", "diamond",
        "forall", "exists", "nexists", "emptyset", "varnothing",
        "infty", "aleph", "hbar", "hslash",
        "imath", "jmath", "ell", "wp", "Re", "Im",
        "angle", "measuredangle", "sphericalangle",
        "to", "longrightarrow", "longleftarrow", "longleftrightarrow",
        "rightarrow", "leftarrow", "leftrightarrow",
        "uparrow", "downarrow", "updownarrow",
        "mapsto", "longmapsto", "hookrightarrow", "hookleftarrow",
        "rightharpoonup", "rightharpoondown", "leftharpoonup", "leftharpoondown",
        "rightleftharpoons", "leftrightharpoons",
        "Rightarrow", "Leftarrow", "Leftrightarrow",
        "Longrightarrow", "Longleftarrow", "Longleftrightarrow",
        "approx", "sim", "simeq", "cong", "equiv",
        "propto", "neq", "ne", "pm", "mp",
        "times", "div", "cdot", "ast", "star",
        "otimes", "oplus", "ominus", "odot", "oslash",
        "cap", "cup", "setminus", "subset", "supset",
        "in", "ni", "notin", "owns",
        "leq", "geq", "ll", "gg",
        "parallel", "perp",
        "doteq", "coloneqq", "eqqcolon", "eqcirc", "circeq",
        "triangleq", "bumpeq", "Bumpeq",
        "thicksim", "thickapprox", "approxeq",
        "lll", "ggg", "lessdot", "gtrdot", "lesseqgtr", "gtreqless",
        "lesssim", "gtrsim", "lessapprox", "gtrapprox",
        "subseteq", "supseteq", "subsetneq", "supsetneq",
        "sqsubset", "sqsupset", "sqsubseteq", "sqsupseteq",
        "smile", "frown", "bowtie", "Join",
        "ldots", "cdots", "vdots", "ddots", "iddots",
        "xleftarrow", "xrightarrow", "xleftrightarrow",
        "xLeftarrow", "xRightarrow", "xLeftrightarrow",
        "xhookleftarrow", "xhookrightarrow",
        "xlongequal", "xmapsto",
        "mathbin", "mathrel", "mathopen", "mathclose", "mathpunct", "mathord",
        "displaystyle", "textstyle", "scriptstyle", "scriptscriptstyle",

        // ── Spacing ──
        "quad", "qquad", "enspace", "thinspace", "negthinspace",
        "medspace", "negmedspace", "thickspace", "negthickspace",
        "hspace", "vspace", "kern", "mkern",

        // ── Boxes / Layout ──
        "mbox", "makebox", "framebox", "fbox", "raisebox",
        "parbox", "minipage", "vspace", "vskip",
        "noindent", "indent", "newline", "linebreak", "pagebreak",
        "newpage", "clearpage", "cleardoublepage",
        "centering", "raggedright", "raggedleft",

        // ── Counters / lengths ──
        "setcounter", "addtocounter", "stepcounter", "value",
        "newcounter", "the", "arabic", "roman", "Roman", "alph", "Alph",
        "fnsymbol",

        // ── References ──
        "label", "ref", "eqref", "pageref", "cite", "nocite",
        "bibliography", "bibliographystyle",
        "footnote", "footnotemark", "footnotetext",

        // ── CircuitikZ  (bipole names usable as to[...]) ──
        "resistor", "american resistor", "european resistor",
        "variable resistor", "variable american resistor", "variable european resistor",
        "potentiometer", "american potentiometer", "european potentiometer",
        "thermistor", "thermistorptc", "thermistorntc",
        "varistor", "photoresistor",
        "capacitor", "american capacitor", "european capacitor",
        "variable capacitor", "variable american capacitor",
        "inductor", "american inductor", "european inductor",
        "cute inductor", "variable inductor", "variable american inductor",
        "transformer", "transformer core",
        "battery", "battery1", "battery2",
        "vsource", "vsourceAM", "vsourceAC",
        "isource", "isourceAM", "isourceAC",
        "vsourceSIN", "isourceSIN",
        "cvsource", "cvsourcesin", "cisource", "cisourcesin",
        "controlled voltage source", "controlled current source",
        "diode", "empty diode", "full diode",
        "Zener diode", "empty Zener diode", "full Zener diode",
        "Schottky diode", "tunnel diode", "LED", "empty LED",
        "photo diode", "empty photo diode",
        "lamp", "bulb",
        "switch", "cute switch", "push button",
        "toggle switch", "closing switch", "opening switch",
        "relay",
        "ground", "eground", "cground", "sground", "tground", "rground", "nground",
        "antenna", "rxantenna", "txantenna",
        "ammeter", "voltmeter", "ohmmeter", "galvanometer",
        "iloop", "multimeter", "qiprobe", "qiport", "oscope",
        "generator", "motor",
        "speaker", "loudspeaker", "microphone", "buzzer",
        "op amp", "op amp inverting", "op amp noninverting",
        "american and port", "american or port",
        "american not port", "american nand port",
        "american nor port", "american xor port", "american xnor port",
        "european and port", "european or port",
        "european not port", "european nand port",
        "european nor port", "european xor port", "european xnor port",
        "buffer port", "tri state port", "not port",
        "vactrol", "memristor", "fuse", "afuse",
        "oscillator", "amplifier", "filter", "mixer",
        "coupler", "circulator", "phase shifter", "attenuator", "detector",
        "thyristor", "triac",
        "spst", "spdt",
        "TL", "R", "C", "L", "D", "V", "I", "Q",
        "empty", "full",
        "wire", "open", "short",

        // ── More TeX basics ──
        "title", "author", "date", "maketitle",
        "chapter", "section", "subsection", "subsubsection",
        "paragraph", "subparagraph",
        "textbf", "textit", "texttt", "textsf", "textsc",
        "emph",
        "url", "href",
        "includegraphics", "graphicspath",
        "color", "textcolor", "colorbox", "fcolorbox", "pagecolor",
        "epsilon",
    };
    return list;
}

inline const QStringList tikzEnvironments() {
    static const QStringList list = {
        "tikzpicture", "scope", "pgfonlayer",
        "axis", "semilogxaxis", "semilogyaxis", "loglogaxis",
        "polaraxis", "smithchart", "ternaryaxis",
        "groupplot", "polarplot",
        "datavisualization",
        "tikzcd",
        "forest",
        "mindmap",
        "feynman",
        "circuitikz",
        "filecontents", "filecontents*",
        "comment",
        "document",
        "center", "flushleft", "flushright",
        "itemize", "enumerate", "description",
        "figure", "table", "minipage",
        "align", "align*",
        "equation", "equation*",
        "displaymath", "math",
        "abstract", "proof", "theorem", "lemma", "corollary", "definition",
        "remark", "example", "proposition", "conjecture",
        "array",
        "matrix", "pmatrix", "bmatrix", "Bmatrix", "vmatrix", "Vmatrix",
        "cases", "split", "gathered", "aligned", "alignedat",
        "gather", "gather*", "multline", "multline*",
        "tabularx", "longtable", "tabular",
        "wrapfigure", "wraptable",
        "subfigure", "figure",
        "tcolorbox",
        "overpic",
        "lstlisting",
        "quote", "quotation", "verse",
        "appendix",
        "thebibliography",
        "titlepage",
        "frame",
        "landscape",
        "sidewaysfigure", "sidewaystable",
        "pgfinterruptboundingbox",
    };
    return list;
}

inline const QStringList tikzOptions() {
    static const QStringList list = {
        // ── Basic positioning ──
        "above", "above left", "above right",
        "below", "below left", "below right",
        "left", "right",
        "align", "allow upside down", "anchor", "angle", "append after command",
        "arrow",
        "ball color", "baseline", "bend angle", "bend at end", "bend at start",
        "bend left", "bend pos", "bend right", "blend mode",
        "cap", "cells", "check",
        "circle", "circular drop shadow",
        "color", "column sep", "columns",
        "dash", "dash dot", "dash dot dot", "dash phase", "dashed",
        "densely dash dot", "densely dash dot dot", "densely dashed", "densely dotted",
        "decorate", "decoration",
        "diamond", "distance", "domain", "dot", "dotted",
        "double", "double distance", "double equal sign distance",
        "draw", "draw opacity", "drop shadow",
        "ellipse", "end angle", "end point",
        "every edge", "every loop", "every node",
        "fill", "fill opacity", "filldraw", "font", "fontsize",
        "green", "grow", "grow cyclic",
        "huge", "hyper",
        "in", "inner color", "inner sep", "inner xsep", "inner ysep",
        "join", "join round",
        "label",
        "late options", "left color", "left delimiter", "left=of",
        "level distance", "line cap", "line join", "line width",
        "looseness", "loosely dash dot", "loosely dash dot dot",
        "loosely dashed", "loosely dotted",
        "matrix of math nodes", "matrix of nodes",
        "mid", "middle color", "midway",
        "minimum height", "minimum size", "minimum width",
        "name", "name prefix", "name suffix", "near end", "near start",
        "node contents", "node distance", "nodes",
        "on background layer", "on grid", "opacity",
        "outer color", "outer sep", "outer xsep", "outer ysep",
        "outline", "overlay",
        "pattern", "pattern color", "pattern type",
        "pin", "pin distance", "pin edge", "pin position",
        "pos", "postaction", "preaction", "prefix after command",
        "radius", "rectangle", "red",
        "regular polygon", "regular polygon sides",
        "remember picture", "right color", "right delimiter", "right=of",
        "rotate", "rotate around", "rounded corners",
        "row sep", "rows",
        "samples", "scale", "scale around", "semithick",
        "shape", "shorten <", "shorten >", "sibling distance",
        "sin", "size", "sloped", "smooth", "solid",
        "star", "star point height", "star point ratio",
        "start", "start angle", "start point",
        "stealth", "step",
        "tension", "text", "text centered", "text depth",
        "text height", "text opacity", "text width",
        "thick", "thin", "tight", "to path", "top color",
        "transform", "transform canvas", "transform shape",
        "triangle",
        "ultra thick", "ultra thin",
        "variable",
        "very thick", "very thin", "visible on",
        "x", "x radius", "xcomb", "xlabel", "xmax", "xmin", "xmode",
        "xscale", "xshift", "xslant", "xstep", "xtick", "xticklabels",
        "y", "y radius", "ycomb", "ylabel", "ymax", "ymin",
        "yscale", "yshift", "yslant", "ystep", "ytick", "yticklabels",
        "z", "zlabel",

        // ── More positioning ──
        "above=of", "below=of", "left=of", "right=of",
        "above left=of", "above right=of",
        "below left=of", "below right=of",
        "at", "at start", "at end", "very near start", "very near end",

        // ── pgfplots axis ──
        "ymode", "zmode",
        "xlabel", "ylabel", "zlabel",
        "xmin", "xmax", "ymin", "ymax", "zmin", "zmax",
        "xtick", "ytick", "ztick",
        "xticklabels", "yticklabels", "zticklabels",
        "minor xtick", "minor ytick", "minor ztick",
        "x tick label style", "y tick label style",
        "x dir", "y dir", "z dir",
        "x filter", "y filter", "z filter",
        "xbar", "ybar", "xbar interval", "ybar interval",
        "xcomb", "ycomb",
        "only marks", "mark", "mark size", "mark options",
        "no markers",
        "smooth", "sharp plot",
        "const plot", "const plot mark left", "const plot mark right",
        "jump mark left", "jump mark right",
        "ybar", "ybar interval",
        "error bars", "error bars/y dir", "error bars/x dir",
        "error bars/y fixed", "error bars/x fixed",
        "title", "legend entries", "legend pos", "legend style",
        "colorbar", "colorbar style",
        "colormap", "colormap name",
        "view",
        "axis equal", "axis equal image",
        "scale mode",
        "restrict x to domain", "restrict y to domain",
        "unbounded coords",
        "hide axis", "hide x axis", "hide y axis",
        "grid", "grid style",
        "major grid style", "minor grid style",
        "minor tick num",
        "enlargelimits",
        "enlarge x limits", "enlarge y limits",
        "width", "height",
        "scaled x ticks", "scaled y ticks",
        "xticklabel style", "yticklabel style",
        "xtick pos", "ytick pos",
        "axis x line", "axis y line",
        "axis line style",

        // ── CircuitikZ  keys ──
        "american", "european",
        "american voltages", "european voltages",
        "american currents", "european currents",
        "american resistors", "european resistors",
        "american capacitors", "european capacitors",
        "american inductors", "european inductors",
        "american ports", "european ports",
        "cute inductors",
        "straight voltages", "curved voltages",
        "voltage shift", "current shift",
        "voltage dir", "oldvoltagedirection", "nooldvoltagedirection",
        "RPvoltages", "EFvoltages",
        "no input leads", "input leads",
        "european logic ports",
        "american logic ports",
        "straight", "curved",
        "mirror", "invert",
        "bipoles", "tripoles", "quadpoles",

        // ── CircuitikZ  component keys ──
        "wiper pos", "wiper end",
        "resistors/scale", "resistors/width", "resistors/thickness",
        "capacitors/scale", "capacitors/width", "capacitors/thickness",
        "inductors/scale", "inductors/width", "inductors/thickness",
        "diodes/scale",
        "batteries/scale",
        "grounds/scale",
        "instruments/scale",
        "amplifiers/scale",
        "logic ports/scale",
        "logic ports origin",
        "american tripoles",
        "european tripoles",

        // ── tikz-3dplot keys ──
        "tdplot_main_coords",
        "tdplot_rotated_coords",
        "tdplot_main_coords_style",
        "tdplot_rotated_coords_style",
        "tdplot_screen_coords",
        "canvas is xy plane at z",
        "canvas is xz plane at y",
        "canvas is yz plane at x",
        "canvas is plane",
        "plane x", "plane y", "plane z",
        "plane origin",
        "projected coordinate",
        "theta", "phi", "r",
        "radius",

        // ── Arrows meta ──
        "arrows", "arrows.meta",
        "Stealth", "Latex", "To",
        "Circle", "Diamond", "Square",
        "Bar", "Bracket", "Parenthesis",
        "Round Cap", "Butt Cap", "Triangle Cap",
        "Fast Round", "Fast Triangle",
        "Straight Barb", "Arc Barb",
        "Hooks", "Implies",
        "Computer Modern Rightarrow", "Classical TikZ Rightarrow",
        "-Stealth", "Stealth-", "-Latex", "Latex-",
        "->", "<-", "<->", ">-<",
        "|-", "-|", "|->", "<-|",
        "->>", "<<-",
        "stealth-stealth", "latex-latex",
        "tip", "tips",

        // ── More general options ──
        "rounded rectangle", "chamfered rectangle",
        "trapezium", "trapezium angle", "trapezium stretches",
        "cylinder", "cylinder uses custom fill",
        "cylinder end fill", "cylinder body fill",
        "tape", "tape bend top", "tape bend bottom",
        "cloud", "cloud ignores aspect",
        "cloud puffs", "cloud puff arc",
        "forbidden sign",
        "cross out", "strike out",
        "magnifying glass",
        "dart", "dart tip angle",
        "kite", "kite vertex angles",
        "signal", "signal pointer angle",
        "single arrow", "single arrow head extend",
        "isosceles triangle",
        "right angle", "right angle length",
        "aspect", "end",
        "polygon", "shape border rotate",
        "shape border uses incircle",
        "text along path",
        "background rectangle",
        "show background rectangle",
        "framed",
        "tight background",
        "loose background",

        // ── Patterns ──
        "horizontal lines", "vertical lines",
        "north east lines", "north west lines",
        "crosshatch", "crosshatch dots",
        "fivepointed stars", "sixpointed stars",
        "bricks", "checkerboard",
        "dots", "grid",
        "checkerboard light gray",

        // ── Decorations ──
        "text along path",
        "text effects along path",
        "random steps", "snake", "coil",
        "saw", "zigzag", "bumps",
        "border", "brace", "footprints",
        "Koch snowflake", "Koch curve type 1", "Koch curve type 2",
        "Cantor set",
        "lineto", "curveto", "moveto", "closepath",
        "markings", "mark", "mark=at position",

        // ── Arrows decoration ──
        "amplitude", "segment length", "segment amplitude",
        "segment angle", "aspect",
        "post length", "pre length",

        // ── More graph/tree ──
        "edge label", "edge label'",
        "edge from parent", "edge from parent path",
        "level 1/.style", "level 2/.style",
        "grow'",
        "grow=up", "grow=down", "grow=left", "grow=right",
        "grow=north", "grow=south", "grow=east", "grow=west",
        "branch",
        "mindmap",
        "concept", "extra concept", "concept color",
        "annotation",
        "circular sector",
        "level/.style",
        "counterclockwise", "clockwise",

        // ── More fit / background ──
        "inner xsep", "inner ysep",
        "fitting node",
        "every fit",
        "framed",

        // ── More misc ──
        "alias", "behind path", "in front of path",
        "after path",
        "path only", "draw=none", "fill=none",
        "transparent",
        "visible on",
        "alt",
        "temporal",
        "uncover", "only", "visible", "invisible",
        "overlay-beamer-styles",
        "execute at begin node", "execute at end node",
        "execute at begin cell", "execute at end cell",
        "execute at begin picture", "execute at end picture",
        "prefix",
        "auto", "swap",
        "accepting", "accepting by arrow", "accepting text",
        "initial", "initial by arrow", "initial text", "initial distance",
        "loop above", "loop below", "loop left", "loop right",
        "every state",
        "state without output",

        // ── Mindmap / trees ──
        "snake", "zigzag", "straight",

        // ── More node shapes ──
        "coordinate", "rectangle split", "rectangle split parts",
        "rectangle split horizontal",
        "circle split", "ellipse split",
        "circle solidus", "ellipse solidus",
        "arrow box", "arrow box arrows",
        "arrow box shaft width", "arrow box head extend",
        "arrow box tip angle",
    };
    return list;
}

inline const QStringList tikzAnchors() {
    static const QStringList list = {
        "north", "south", "east", "west",
        "north east", "north west", "south east", "south west",
        "center", "base", "base east", "base west",
        "mid", "mid east", "mid west",
        "text", "text split",
        "left", "right", "top", "bottom",
        "apex", "corner 1", "corner 2", "tail",
        "input", "output", "input 1", "input 2", "output 1", "output 2",
        "north east corner", "north west corner", "south east corner", "south west corner",
        "angle",
        "150", "120", "90", "60", "30", "0",
        "210", "240", "270", "300", "330",

        // ── CircuitikZ  anchors ──
        "wiper", "wiper start", "wiper end",
        "cathode", "anode",
        "base", "collector", "emitter",
        "gate", "drain", "source", "bulk",
        "in", "out", "up", "down",
        "in 1", "in 2", "out",
        "left in", "left out", "right in", "right out",
        "left up", "left down", "right up", "right down",
        "bgate", "sgate", "cin", "cout",
        "vin", "vout", "iin", "iout",
        "G", "D", "S",
        "B", "C", "E",
        "north in", "north out",
        "south in", "south out",
        "east in", "east out",
        "west in", "west out",
        "+", "-",
        "v+", "v-",
        "body",
        "left body", "right body",
        "left anchor", "right anchor",

        // ── More anchors ──
        "before top", "after top",
        "before bottom", "after bottom",
        "split north", "split south", "split east", "split west",
        "second north", "second south", "second east", "second west",
        "third north", "third south",
        "fourth north", "fourth south",
        "first", "second", "third", "fourth",
        "arc start", "arc end",
        "start", "end",
        "head north", "head south",
        "tail north", "tail south",
        "text center",
        "pin center",
        "below center", "above center",
        "north of center", "south of center",
        "east of center", "west of center",
        "right side base", "left side base",
    };
    return list;
}

inline const QStringList tikzColors() {
    static const QStringList list = {
        "red", "green", "blue", "cyan", "magenta", "yellow", "black",
        "white", "gray", "darkgray", "lightgray", "brown",
        "orange", "purple", "violet", "pink", "olive", "teal", "lime",
        "darkblue", "darkgreen", "darkred", "darkcyan", "darkmagenta",
        "darkyellow", "darkorange", "darkpurple", "darkviolet",
        "lightblue", "lightgreen", "lightred", "lightcyan", "lightmagenta",
        "lightyellow", "lightorange", "lightpink",
        "copper", "gold", "silver", "bronze",

        // ── Extended xcolor / dvipsnames ──
        "Apricot", "Aquamarine", "Bittersweet", "BlueGreen",
        "BlueViolet", "BrickRed", "BurntOrange", "CadetBlue",
        "CarnationPink", "Cerulean", "CornflowerBlue", "Dandelion",
        "Emerald", "ForestGreen", "Fuchsia", "Goldenrod",
        "Gray", "GreenYellow", "JungleGreen", "Lavender",
        "LimeGreen", "Magenta", "Mahogany", "Maroon", "Melon",
        "MidnightBlue", "Mulberry", "NavyBlue", "OrangeRed",
        "Orchid", "Peach", "Periwinkle", "PineGreen", "Plum",
        "ProcessBlue", "RawSienna", "RedOrange", "RedViolet",
        "Rhodamine", "RoyalBlue", "RoyalPurple", "RubineRed",
        "Salmon", "SeaGreen", "Sepia", "SkyBlue", "SpringGreen",
        "Tan", "Thistle", "Turquoise", "VioletRed",
        "WildStrawberry", "YellowGreen", "YellowOrange",
    };
    return list;
}

inline const QStringList tikzArrows() {
    static const QStringList list = {
        "stealth", "stealth'", "latex", "latex reversed", "to", "to reversed",
        "angle 90", "angle 60", "angle 45",
        "triangle 90", "triangle 60", "triangle 45",
        "open triangle 90", "open triangle 60", "open triangle 45",
        "Circle", "Diamond", "Square",
        "Bar", "Bracket", "Parenthesis",
        "Round Cap", "Butt Cap", "Triangle Cap",
        "Fast Round", "Fast Triangle",
        "Hooks", "Implies", "Straight Barb",
        "Arc Barb", "Classical TikZ Rightarrow",
        "Computer Modern Rightarrow",
        "Rays", "Tee Barb", "Kite",
        "Turned Square", "Ellipse",
        "Stealth", "Latex", "To",
        "Right to", "Left to",
    };
    return list;
}

inline const QStringList tikzLineTypes() {
    static const QStringList list = {
        "solid", "dashed", "dotted", "dash dot", "dash dot dot",
        "loosely dashed", "densely dashed",
        "loosely dotted", "densely dotted",
        "loosely dash dot", "densely dash dot",
        "loosely dash dot dot", "densely dash dot dot",
        "dashdotted", "densely dashdotted", "loosely dashdotted",
    };
    return list;
}

inline const QStringList tikzLineWidths() {
    static const QStringList list = {
        "ultra thin", "very thin", "thin", "semithick",
        "thick", "very thick", "ultra thick",
    };
    return list;
}

inline const QStringList tikzMathFunctions() {
    static const QStringList list = {
        "abs", "acos", "add", "angle", "asin", "atan", "atan2",
        "ceil", "cit", "clip", "cm", "cos", "cosec", "cosh",
        "cot", "deg", "depth", "dim", "divide", "dotproduct",
        "e", "exp",
        "factorial", "floor", "format",
        "frac", "gcd", "height",
        "in", "int", "intersection", "isodd",
        "kil", "length", "ln", "log10", "log2",
        "max", "min", "mod", "multiply",
        "not", "note",
        "pi", "pow", "power",
        "pt",
        "rad", "rand", "random", "rdiv", "real", "record", "res",
        "round", "scalar", "sec", "sign", "sin", "sinh",
        "sqrt", "subtract", "sum",
        "tan", "tanh", "true", "turn",
        "value", "vecilen", "width",

        // ── Extended math functions ──
        "acos", "acosec", "acosech", "acosh", "acot", "acoth",
        "acsc", "acsch", "asec", "asech", "divmod",
        "equalto", "greaterthan", "lessthan", "notequalto",
        "notless", "notgreater",
        "or", "and",
        "pi", "deg", "rad",
        "sprintf",
        "strcat", "strcmp", "strlen", "substr",
        "array", "dim", "empty",
        "x", "y", "z",
        "atan2deg", "cosdeg", "sindeg", "tandeg",
        "acotdeg", "acosdeg", "asindeg",
    };
    return list;
}

inline QStringList tikzLineWidthValues() {
    return {"0.2pt","0.4pt","0.5pt","0.6pt","0.8pt","1pt","1.2pt","1.5pt","2pt","2.5pt","3pt","4pt","5pt","6pt","8pt","10pt","12pt","15pt","20pt"};
}

inline QStringList tikzArrowValues() {
    return {"stealth", "latex", "to", "angle 90", "angle 60", "triangle 90",
            "Triangle", "Circle", "Diamond", "Square", "Bar", "Bracket",
            "Parenthesis", "Round Cap", "Butt Cap", "Triangle Cap",
            "Fast Round", "Fast Triangle", "Straight Barb", "Arc Barb",
            "Computer Modern Rightarrow", "Implies", "Hooks", "Classical TikZ Rightarrow",
            "Rays", "Tee Barb", "Kite", "Turned Square", "Right to", "Left to"};
}

using WordPair = QPair<QString, QStringList>;

inline QVector<WordPair> tikzValueHints() {
    static const QVector<WordPair> hints = {
        // ── Colors ──
        {"color", tikzColors()},
        {"draw", tikzColors()},
        {"fill", tikzColors()},
        {"left color", tikzColors()},
        {"right color", tikzColors()},
        {"middle color", tikzColors()},
        {"top color", tikzColors()},
        {"bottom color", tikzColors()},
        {"inner color", tikzColors()},
        {"outer color", tikzColors()},
        {"ball color", tikzColors()},
        {"pattern color", tikzColors()},
        {"text", tikzColors()},
        {"concept color", tikzColors()},

        // ── Arrows ──
        {"arrow", tikzArrowValues()},
        {"-", tikzArrowValues()},
        {"arrows", tikzArrowValues()},
        {"mark", {"*", "x", "+", "-", "|", "o", "asterisk", "star",
                  "10-pointed star", "oplus", "oplus*",
                  "otimes", "otimes*", "square", "square*",
                  "triangle", "triangle*", "diamond", "diamond*",
                  "halfdiamond*", "halfsquare*", "halfcircle*",
                  "pentagon", "pentagon*",
                  "Mercedes star", "Mercedes star flipped",
                  "halfcircle", "heart", "text", "none"}},

        // ── Line widths ──
        {"line width", tikzLineWidthValues()},
        {"ultra thin", {}},
        {"very thin", {}},
        {"thin", {}},
        {"semithick", {}},
        {"thick", {}},
        {"very thick", {}},
        {"ultra thick", {}},

        // ── Line caps/joins ──
        {"cap", {"butt", "round", "rect"}},
        {"line cap", {"butt", "round", "rect"}},
        {"join", {"round", "bevel", "miter"}},
        {"line join", {"round", "bevel", "miter"}},
        {"miter limit", {"1", "2", "4", "8", "10"}},

        // ── Alignment ──
        {"align", {"left", "center", "right", "justify", "none", "flush left", "flush right"}},
        {"anchor", tikzAnchors()},
        {"pin position", tikzAnchors()},

        // ── Bend ──
        {"bend left", {"90","60","45","30","15","0"}},
        {"bend right", {"90","60","45","30","15","0"}},
        {"bend angle", {"90","60","45","30","15","10","5"}},

        // ── Rotation ──
        {"rotate", {"90","180","270","45","60","30","15","-90","-180","-45","0"}},
        {"angle", {"90","60","45","30","180","270","0"}},
        {"shape border rotate", {"90","180","270","45","30","60","0"}},

        // ── Scale ──
        {"scale", {"0.5","0.8","1.0","1.2","1.5","2.0","3.0"}},
        {"xscale", {"0.5","0.8","1.0","1.2","1.5","2.0"}},
        {"yscale", {"0.5","0.8","1.0","1.2","1.5","2.0"}},

        // ── Opacity ──
        {"opacity", {"0.1","0.2","0.3","0.4","0.5","0.6","0.7","0.8","0.9","1.0"}},
        {"draw opacity", {"0.3","0.5","0.7","1.0"}},
        {"fill opacity", {"0.3","0.5","0.7","1.0"}},
        {"text opacity", {"0.5","0.7","1.0"}},

        // ── Size / length ──
        {"text width", {"2cm","3cm","4cm","5cm","6cm","8cm","10cm","12cm"}},
        {"minimum width", {"0.5cm","1cm","1.5cm","2cm","3cm","4cm","5cm","8cm"}},
        {"minimum height", {"0.5cm","1cm","1.5cm","2cm","3cm","4cm","5cm","8cm"}},
        {"minimum size", {"0.5cm","1cm","1.5cm","2cm","3cm","4cm","5cm","8cm"}},
        {"inner sep", {"0pt","1pt","2pt","3pt","4pt","5pt","6pt","8pt","10pt"}},
        {"outer sep", {"0pt","1pt","2pt","3pt","4pt","5pt"}},
        {"inner xsep", {"0pt","2pt","4pt","6pt","8pt","10pt"}},
        {"inner ysep", {"0pt","2pt","4pt","6pt","8pt","10pt"}},
        {"node distance", {"0.5cm","1cm","1.5cm","2cm","2.5cm","3cm","4cm"}},
        {"level distance", {"0.5cm","1cm","1.5cm","2cm","3cm","4cm"}},
        {"sibling distance", {"0.5cm","1cm","1.5cm","2cm","3cm","4cm"}},
        {"rounded corners", {"1pt","2pt","3pt","4pt","5pt","8pt","10pt","12pt"}},
        {"double distance", {"1pt","1.5pt","2pt","3pt","4pt","5pt"}},
        {"shorten <", {"1pt","2pt","3pt","5pt","8pt","10pt"}},
        {"shorten >", {"1pt","2pt","3pt","5pt","8pt","10pt"}},
        {"radius", {"0.5cm","1cm","1.5cm","2cm","3cm","4cm","5cm"}},
        {"x radius", {"0.5cm","1cm","1.5cm","2cm","3cm"}},
        {"y radius", {"0.5cm","1cm","1.5cm","2cm","3cm"}},
        {"size", {"0.5cm","1cm","1.5cm","2cm","3cm"}},

        // ── pgfplots ──
        {"samples", {"50","100","200","500","1000"}},
        {"domain", {"0:10","0:1","-5:5","-10:10","-pi:pi","0:2*pi","-2:2"}},
        {"regular polygon sides", {"3","4","5","6","7","8","10","12"}},
        {"star point ratio", {"0.3","0.4","0.5","0.6","0.8","1.0"}},
        {"star point height", {"0.5cm","0.8cm","1cm","1.5cm","2cm"}},
        {"rectangle split parts", {"2","3","4","5","6"}},

        // ── More pgfplots keys ──
        {"mark size", {"1pt","2pt","3pt","4pt","5pt","6pt","8pt"}},
        {"xmode", {"normal", "log"}},
        {"ymode", {"normal", "log"}},
        {"legend pos", {"north east", "north west", "south east", "south west",
                        "outer north east"}},
        {"view", {"{0}{90}", "{45}{45}", "{90}{0}", "{30}{30}"}},

        // ── Arrows decoration ──
        {"amplitude", {"1pt","2pt","3pt","4pt","5pt","8pt","10pt"}},
        {"segment length", {"2pt","3pt","4pt","5pt","8pt","10pt"}},
        {"segment amplitude", {"1pt","2pt","3pt","4pt","5pt"}},
        {"post length", {"1pt","2pt","3pt","5pt"}},
        {"pre length", {"1pt","2pt","3pt","5pt"}},
    };
    return hints;
}

inline QStringList allCompletableWords() {
    QStringList result;
    result << tikzCommands() << tikzOptions() << tikzAnchors()
           << tikzColors() << tikzArrows()
           << tikzLineTypes() << tikzLineWidths()
           << tikzMathFunctions() << tikzArrowValues()
           << tikzLineWidthValues();
    result.removeDuplicates();
    result.sort(Qt::CaseInsensitive);
    return result;
}

inline const QStringList &pgfKeysPathCommands() {
    static const QStringList list = {
        "/tikz", "/pgf", "/pgfplots", "/graph",
        "/tikz/every picture", "/tikz/every node", "/tikz/every path",
        "/tikz/every edge", "/tikz/every label", "/tikz/every pin",
        "/tikz/every graph", "/tikz/every plot",
        "/tikz/every scope",
        "/pgf/number format",
        "/pgfplots/legend",
        "/circuitikz",
        "/circuitikz/bipoles",
        "/circuitikz/tripoles",
        "/circuitikz/quadpoles",
        "/circuitikz/voltage",
        "/circuitikz/current",
        "/circuitikz/resistor",
        "/circuitikz/capacitor",
        "/circuitikz/inductor",
        "/circuitikz/diode",
        "/circuitikz/logic ports",
        "/circuitikz/grounds",
    };
    return list;
}

} // namespace TikzWords
